name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: "kinetic",
            ROS_REPO: "main",
            OPT_VI: "-vi",
            CATKIN_LINT: "true",
            ROSDEP_SKIP_KEYS: "phoxi_camera",
            UPSTREAM_WORKSPACE: ".depends.rosinstall",
            AFTER_SETUP_TARGET_SCRIPT: "./.pre_process.sh",
            CATKIN_LINT_ARGS: "--ignore unknown_package",
            }

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
